Feature/add generic datatable
Boman2001/pharma-angular pull request #39
Opened 2021-01-13 11:01 UTC by Thomas-Terlaak

2021-01-13 18:01 UTC, Boman2001 requested changes
joo @Thomas-Terlaak je tests falen

2021-01-14 09:39 UTC, ZiasLuijkx approved these changes

2021-01-14 09:40 UTC, Boman2001 approved these changes

2021-01-14 09:44 UTC, Boman2001 commented
word gemerged als @julesmons   het mooier maakt in zijn branch

2021-01-14 09:44 UTC, merged