Add 2fa
Boman2001/pharma-angular pull request #54
Opened 2021-01-18 14:44 UTC by Boman2001

2021-01-18 14:49 UTC, ZiasLuijkx requested changes
Waarom is de package-lock.json weer -18k regels?

2021-01-18 14:49 UTC, ZiasLuijkx commented on src/app/modules/auth/pages/two-factor/two-factor.component.html
> +    <p>please scan the code with microsoft authenticator </p>
Hoofdletter en in het Nederlands

2021-01-18 14:49 UTC, ZiasLuijkx commented on src/app/modules/auth/pages/two-factor/two-factor.component.html
> +        <div class="input-validation-error-text" *ngIf="form.controls['authCode'].errors.required">Code is required</div>
Nederlands

2021-01-18 14:53 UTC, Thomas-Terlaak approved these changes

2021-01-19 09:13 UTC, leanderoudakker requested changes

2021-01-19 09:13 UTC, leanderoudakker commented on src/app/modules/auth/models/TwoFactorResponse.model.ts
> +
Extra blank line

2021-01-19 09:33 UTC, ZiasLuijkx approved these changes

2021-01-19 09:34 UTC, leanderoudakker approved these changes

2021-01-19 10:45 UTC, merged